

language: node_js

node_js:
  - "6"
jdk:
  - oraclejdk8
cache:
  directories:
    - node_modules


# Make chrome browser available for testing
before_install:
  - java -version
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux32.zip
  - unzip chromedriver_linux32.zip
  - wget http://selenium-release.storage.googleapis.com/3.3/selenium-server-standalone-3.3.1.jar
  - java -jar selenium-server-standalone-3.3.1.jar
  - sh -e /etc/init.d/xvfb start


install:
  - npm install

script:
  - npm run build
