sudo: true
language: node_js

node_js:
  - "6"


cache:
  directories:
    - node_modules
branches:
  only: master

notifications:
  email: false


# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sudo chmod 4755 /usr/lib/chromium-browser/chrome-sandbox

  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start


install:
  - npm install

script:
  - karma start
