language: node_js

node_js:
  - "6"

addons:
  firefox: "49.0"
cache:
  directories:
    - node_modules
branches:
  only: master

notifications:
  email: false


# Make chrome browser available for testing
before_install:
  - export DISPLAY=:99.0

  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start


install:
  - npm install

script:
  - karma start
