

language: node_js

node_js:
  - "6"
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
            - oracle-java8-set-default
cache:
  directories:
    - node_modules
notifications:
  email: false


# Make chrome browser available for testing
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - echo "javascript版本号"
  - java -version
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - echo "Download selenium-server-standalone jar file"
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - wget http://selenium-release.storage.googleapis.com/3.3/selenium-server-standalone-3.3.1.jar
  - echo "Run selenium server - background process"
  - nohup bash -c "java -jar selenium-server-standalone-3.3.1.jar &" && sleep 1; cat nohup.out

install:
  - npm install

script:
  - npm run build
