

language: java node_js

node_js:
  - "6"
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
            - oracle-java8-set-default
cache:
  directories:
    - node_modules
notifications:
  email: false


# Make chrome browser available for testing
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - wget http://selenium-release.storage.googleapis.com/3.3/selenium-server-standalone-3.3.1.jar


install:
  - npm install
before_script:
  - java -jar selenium-server-standalone-3.3.1.jar
script:
  - npm run build
