version: 2

defaults: &defaults
  working_directory: ~/anu
  docker:
    - image: circleci/node:8.10.0
  branches:
      only:
        - branch3

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: install anu deps
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: test react runtime
          command: npm run test

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          - v2-dependencies-    
      - run:
          name: install cli deps
          command: |
            cd ./packages/cli
            npm install
      - save_cache:
          paths:
            - packages/cli/node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: test cli
          command: |
            cd ./packages/cli
            npm run test
            